[package]
name = "astra-web"
version = "0.1.0"
edition = "2021"

[features]
http2 = ["astra/http2"]

[dependencies]
astra = { git = "https://github.com/ibraheemdev/astra" }
bytes = "1.5.0"
http = "0.2.11"
matchit = "0.7.2"
serde = "1.0.192"